# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.


## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [2]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_name = os.getenv("DB_NAME")

connection_string = (
    f"mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
)

engine = create_engine(connection_string)

print(engine)

Engine(mysql+pymysql://root:***@127.0.0.1:3306/classicmodels)

In [3]:
import pandas as pd
from sqlalchemy import text

columns_query = text("""
    SELECT COLUMN_NAME, DATA_TYPE 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'customers' 
      AND TABLE_SCHEMA = DATABASE()
""")

with engine.connect() as conn:
    df_columns = pd.read_sql(columns_query, conn)

display(df_columns)

               COLUMN_NAME DATA_TYPE
0           customerNumber       int
1             customerName   varchar
2          contactLastName   varchar
3         contactFirstName   varchar
4                    phone   varchar
5             addressLine1   varchar
6             addressLine2   varchar
7                     city   varchar
8                    state   varchar
9               postalCode   varchar
10                 country   varchar
11  salesRepEmployeeNumber       int
12             creditLimit   decimal

In [4]:
def update_customer_contact(customer_number, new_phone=None, new_email=None):
    
    with engine.begin() as conn:
        check_query = text("SELECT customerNumber, customerName, phone FROM customers WHERE customerNumber = :cust_id")
        customer = conn.execute(check_query, {"cust_id": customer_number}).fetchone()
        
        if not customer:
            print(f"Клієнта з номером {customer_number} не знайдено в базі даних.")
            return False
            
        print(f"Знайдено клієнта: {customer.customerName} (ID: {customer.customerNumber})")
        
        cols_query = text("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_NAME = 'customers' AND TABLE_SCHEMA = DATABASE()
        """)
        existing_cols = [row[0] for row in conn.execute(cols_query).fetchall()]
        
        update_fields = []
        params = {"cust_id": customer_number}

        if new_phone is not None:
            if 'phone' in existing_cols:
                update_fields.append("phone = :phone")
                params["phone"] = new_phone
            else:
                print("Поле 'phone' відсутнє у схемі таблиці.")

        if new_email is not None:
            if 'email' in existing_cols:
                update_fields.append("email = :email")
                params["email"] = new_email
            else:
                print("Зверніть увагу: Поле 'email' відсутнє в таблиці customers, тому воно не оновлюється.")

        if not update_fields:
            print("Немає дійсних полів для оновлення.")
            return False

        update_sql = text(f"""
            UPDATE customers
            SET {', '.join(update_fields)}
            WHERE customerNumber = :cust_id
        """)
        
        conn.execute(update_sql, params)
        print(f"Дані для клієнта #{customer_number} успішно оновлено.")
        return True

target_customer_id = 103

print("--- Стан ДО оновлення ---")
df_before = pd.read_sql(
    text("SELECT customerNumber, customerName, phone, city, country FROM customers WHERE customerNumber = :id"),
    engine,
    params={"id": target_customer_id}
)
display(df_before)

update_customer_contact(
    customer_number=target_customer_id,
    new_phone="+380 50 111 22 33",
    new_email="client@example.com"
)

print("\n--- Стан ПІСЛЯ оновлення ---")
df_after = pd.read_sql(
    text("SELECT customerNumber, customerName, phone, city, country FROM customers WHERE customerNumber = :id"),
    engine,
    params={"id": target_customer_id}
)
display(df_after)

--- Стан ДО оновлення ---

   customerNumber       customerName       phone    city country
0             103  Atelier graphique  40.32.2555  Nantes  France

Знайдено клієнта: Atelier graphique (ID: 103)
Зверніть увагу: Поле 'email' відсутнє в таблиці customers, тому воно не оновлюється.
Дані для клієнта #103 успішно оновлено.

--- Стан ПІСЛЯ оновлення ---

   customerNumber       customerName              phone    city country
0             103  Atelier graphique  +380 50 111 22 33  Nantes  France

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [5]:
from datetime import date
import pandas as pd
from sqlalchemy import text

def create_order_with_transaction(customer_number, items, comments="New test order"):
    try:
        with engine.begin() as conn:
            next_order_num = conn.execute(text("SELECT COALESCE(MAX(orderNumber), 10000) + 1 FROM orders")).scalar()

            for item in items:
                prod_check = conn.execute(
                    text("SELECT productName, quantityInStock FROM products WHERE productCode = :code FOR UPDATE"),
                    {"code": item['productCode']}
                ).fetchone()
                
                if not prod_check:
                    raise ValueError(f"Товар з кодом {item['productCode']} не знайдено.")
                
                if prod_check.quantityInStock < item['quantityOrdered']:
                    raise ValueError(
                        f"Недостатньо товару '{prod_check.productName}' на складі! "
                        f"Запитувано: {item['quantityOrdered']}, в наявності: {prod_check.quantityInStock}"
                    )
                    
            conn.execute(
                text("""
                    INSERT INTO orders (orderNumber, orderDate, requiredDate, status, comments, customerNumber)
                    VALUES (:orderNumber, :orderDate, :requiredDate, :status, :comments, :customerNumber)
                """),
                {
                    "orderNumber": next_order_num,
                    "orderDate": date.today(),
                    "requiredDate": date.today(),
                    "status": "In Process",
                    "comments": comments,
                    "customerNumber": customer_number
                }
            )

            for idx, item in enumerate(items, start=1):
                conn.execute(
                    text("""
                        INSERT INTO orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                        VALUES (:orderNumber, :productCode, :quantityOrdered, :priceEach, :orderLineNumber)
                    """),
                    {
                        "orderNumber": next_order_num,
                        "productCode": item['productCode'],
                        "quantityOrdered": item['quantityOrdered'],
                        "priceEach": item['priceEach'],
                        "orderLineNumber": idx
                    }
                )
                
                conn.execute(
                    text("""
                        UPDATE products
                        SET quantityInStock = quantityInStock - :quantity
                        WHERE productCode = :code
                    """),
                    {
                        "quantity": item['quantityOrdered'],
                        "code": item['productCode']
                    }
                )

            print(f"Замовлення #{next_order_num} успішно створено і зафіксовано в транзакції!")
            return next_order_num

    except Exception as e:
        print(f"Помилка створення замовлення (транзакцію скасовано): {e}")
        return None

test_customer = 103
test_items = [
    {'productCode': 'S10_1678', 'quantityOrdered': 5, 'priceEach': 95.70},
    {'productCode': 'S10_1949', 'quantityOrdered': 2, 'priceEach': 190.00}
]

print("--- Залишки на складі ДО оформлення замовлення ---")
codes = [item['productCode'] for item in test_items]
display(pd.read_sql(
    text("SELECT productCode, productName, quantityInStock FROM products WHERE productCode IN :codes"),
    engine,
    params={"codes": tuple(codes)}
))

new_id = create_order_with_transaction(test_customer, test_items)

if new_id:
    print(f"\n--- Перевірка створеного замовлення #{new_id} у таблиці orders ---")
    display(pd.read_sql(
        text("SELECT * FROM orders WHERE orderNumber = :id"),
        engine,
        params={"id": new_id}
    ))

    print(f"\n--- Перевірка доданих товарів у таблиці orderdetails ---")
    display(pd.read_sql(
        text("SELECT * FROM orderdetails WHERE orderNumber = :id"),
        engine,
        params={"id": new_id}
    ))

    print(f"\n--- Залишки на складі ПІСЛЯ оформлення замовлення (зменшились на 5 і 2) ---")
    display(pd.read_sql(
        text("SELECT productCode, productName, quantityInStock FROM products WHERE productCode IN :codes"),
        engine,
        params={"codes": tuple(codes)}
    ))

--- Залишки на складі ДО оформлення замовлення ---

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7933
1    S10_1949               1952 Alpine Renault 1300             7305

Замовлення #10426 успішно створено і зафіксовано в транзакції!

--- Перевірка створеного замовлення #10426 у таблиці orders ---

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10426,2026-10-04,2026-10-04,None,In Process,New test order,103

--- Перевірка доданих товарів у таблиці orderdetails ---

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10426    S10_1678                5       95.7                1
1        10426    S10_1949                2      190.0                2

--- Залишки на складі ПІСЛЯ оформлення замовлення (зменшились на 5 і 2) ---

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7928
1    S10_1949               1952 Alpine Renault 1300             7303